services:
  db:
    image: postgres:16
    container_name: itemsdb
    environment:
      POSTGRES_DB: itemsdb
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "quarkus"]
      interval: 5s
      timeout: 5s
      retries: 12
